### ISSUE TITLE
How to save ssh remote password?

### ISSUE THREAD

**Issue by Sub028** [sund/auto-gitlab-backup#25]
Hi, first of all, i want to thank you for this helpful script!
It works fine manually but each time I launch your script with "/usr/local/sbin/auto-gitlab-backup/auto-gitlab-backup.sh", it asks me the remote ssh password. 
In fact, I can't find option in "auto-gitlab-backup.conf" which refers to remote password. Is it "rsync_password_file"?
Thanks

**Comment by sund** [comment]
Are you using sshkeys? Make sure the user the cron job runs as has access to the key file.

**Comment by Sub028** [comment]
Thanks, it works! By using "ssh-keygen -t rsa" (on local server), i got a ssh public key with i have pasted in "~/.ssh/authorized_keys" (on the remote server).
