### ISSUE TITLE
Auto ssh password

### ISSUE THREAD

**Issue by AmeliaEnslin** [sund/auto-gitlab-backup#47]
hi there

Great script thanx!!! is there a way to automate the ssh password, as currently i need to add the remote dir ssh password before it cab copy the backup to the remote dir. So cant run it automatically

**Comment by sund** [comment]
I think you should look at using [SSH keys](https://help.github.com/articles/connecting-to-github-with-ssh/).

**Comment by AmeliaEnslin** [comment]
tried that but have 22 other pc's to connect to so once i do that i block all the others

**Comment by sund** [comment]
?? you have 22 machines that will use the same server to backup to with the script? Is that correct?

**Comment by sund** [comment]
Hadn't heard back, but assuming you are trying to use the script on 22 servers that backup to the same destination, you are able to use 22 different ssh keys by adding each public key to the same ```.ssh/authorized_keys``` file. Alternately, you could generate a key on one host and copy the private key to the other 21 servers.
